version: '3'

services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports: 
      - '80:3000'
    links: 
      - db
  db:
    container_name: mongo
    image: mongo
    volumes: 
      - ./data/db:/data/db
    ports: 
      - '27017:27017'

